FROM alpine:3.7 as hbs
USER root

ENV FALCON_MODULE="hbs" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache ca-certificates bash

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip

EXPOSE 6031 6030

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/hbs/bin/falcon-hbs", "-c", \
     "/open-falcon/hbs/config/cfg.json"]
