FROM alpine:3.7 as aggregator
USER root

ENV FALCON_MODULE="aggregator" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache bash util-linux

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/ 
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip && \
    mv localtime.shanghai /etc/localtime

EXPOSE 6055

CMD ["./falcon-entry.sh"]
