FROM alpine:latest as api
USER root

ENV FALCON_MODULES="api" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    mkdir -p $FALCON_DIR/logs && \
    apk add --no-cache ca-certificates bash supervisor

COPY . $FALCON_DIR
WORKDIR $FALCON_DIR

RUN mv supervisord.conf.api /etc/supervisord.conf && \
    rm -rf Dockerfile* *.zip

EXPOSE 8080

# Start
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
