FROM harbor.cloudminds.com/library/alpine:3.CM-Beta-1.3
USER root

ENV PROJECT=mcs MODULE=falcon-transfer LOGPATH=

ENV FALCON_MODULE="transfer" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache ca-certificates bash util-linux tcpdump busybox-extras

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip && \
    mv localtime.shanghai /etc/localtime

EXPOSE 6060 8433

CMD ["./falcon-entry.sh"]
