FROM alpine:3.7 as judge
USER root

ENV FALCON_MODULE="judge" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache ca-certificates bash

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip

EXPOSE 6080 6081

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/judge/bin/falcon-judge", "-c", \
     "/open-falcon/judge/config/cfg.json"]
