FROM alpine:3.7 as nodata
USER root

ENV FALCON_MODULES="nodata" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    mkdir -p $FALCON_DIR/logs && \
    apk add --no-cache ca-certificates bash supervisor

COPY . $FALCON_DIR
WORKDIR $FALCON_DIR

RUN mv supervisord.conf.nodata /etc/supervisord.conf && \
    rm -rf Dockerfile* *.zip

EXPOSE 6090

# Start
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
CMD ["/bin/sh", "-c", "./falconctl run"]
