FROM alpine:3.7 as transfer
USER root

ENV FALCON_MODULE="transfer" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache ca-certificates bash

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip

EXPOSE 6060 8433

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/transfer/bin/falcon-transfer", "-c", \
     "/open-falcon/transfer/config/cfg.json"]
