FROM alpine:3.7 as agent
USER root

ENV FALCON_MODULE="agent" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache ca-certificates bash git

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/ 
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip


EXPOSE 1988

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/agent/bin/falcon-agent", "-c", \
     "/open-falcon/agent/config/cfg.json"]
