FROM alpine:3.7 as aggregator
USER root

ENV FALCON_MODULE="aggregator" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache bash

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/ 
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip

EXPOSE 6055

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/aggregator/bin/falcon-aggregator", "-c", \
     "/open-falcon/aggregator/config/cfg.json"]
