FROM alpine:3.7 as graph
USER root

ENV FALCON_MODULE="graph" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    mkdir -p $FALCON_DIR/logs && \
    apk add --no-cache ca-certificates bash util-linux

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip && \
    mv localtime.shanghai /etc/localtime

EXPOSE 6071 6070

CMD ["./falcon-entry.sh"]
