FROM alpine:3.7 as nodata
USER root

ENV FALCON_MODULE="nodata" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    apk add --no-cache ca-certificates bash

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip

EXPOSE 6090

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/nodata/bin/falcon-nodata", "-c", \
     "/open-falcon/nodata/config/cfg.json"]
