FROM alpine:3.7 as api
USER root

ENV FALCON_MODULE="api" \
    FALCON_DIR=/open-falcon 

RUN mkdir -p $FALCON_DIR && \
    mkdir -p $FALCON_DIR/logs && \
    apk add --no-cache ca-certificates bash

COPY . $FALCON_DIR
COPY ./zoneinfo.zip /usr/local/go/lib/time/
WORKDIR $FALCON_DIR

RUN rm -rf Dockerfile* *.zip

EXPOSE 8080

# create config-files by ENV
ENTRYPOINT ["./falcon-entry.sh"]

CMD ["/open-falcon/api/bin/falcon-api", "-c", \
     "/open-falcon/api/config/cfg.json"]
